###GET ALL POSTS

GET http://localhost:3001/api/posts HTTP/1.1


###ADD POST

POST http://localhost:3001/api/posts HTTP/1.1
Content-Type: application/json


{
        "title":"Electromagnetism Mod IV",
        "description":"Electromagnetism notes for last minute",
        "thumbnail":"https://static.docsity.com/documents_first_pages/2013/02/19/cf003fe686eafafc20393ed6b8d90f4c.png",
        "price":"0.0002",
        "subject" :"Physics",
        "department":"AIML",
        "semester":1,
        "firstpage":"https://static.docsity.com/documents_first_pages/2013/02/19/cf003fe686eafafc20393ed6b8d90f4c.png",
        "secondpage":"https://static.docsity.com/documents_first_pages/2013/02/19/cf003fe686eafafc20393ed6b8d90f4c.png",
        "thirdpage":"https://static.docsity.com/documents_first_pages/2013/02/19/cf003fe686eafafc20393ed6b8d90f4c.png"
}